#!/usr/bin/env python3
"""Render reviewed, transactional runtime grants; never read database credentials.

Pipe reviewed output to psql -X -v ON_ERROR_STOP=1 as the separate DDL operator.
Role creation/login secrets and database/HBA policy are separate operator work.
"""
import argparse
import json
from pathlib import Path
import re

IDENT = re.compile(r"[a-z][a-z0-9_]{0,62}\Z")
COMPONENTS = {"api", "ingestion", "notifications", "delivery", "reports", "retention", "operator"}


def identifier(value):
    if not IDENT.fullmatch(value):
        raise ValueError("Identifiers must be lowercase ASCII PostgreSQL names of at most63 bytes")
    return '"' + value + '"'


def render(schema, role, components):
    schema_sql, role_sql = identifier(schema), identifier(role)
    if not components or len(set(components)) != len(components) or not set(components) <= COMPONENTS:
        raise ValueError("Unknown, empty or repeated role components")
    if len(components) > 1 and ("api" in components or "operator" in components):
        raise ValueError("API and read-only operator identities cannot be worker bundles")
    manifest = json.loads(Path(__file__).with_name("grants.json").read_text())
    merged = {}
    for component in components:
        for table, grants in manifest["roles"][component].items():
            identifier(table)
            dest = merged.setdefault(table, {})
            for operation, value in grants.items():
                if operation == "delete":
                    if value is not True:
                        raise ValueError("Invalid DELETE grant")
                    dest[operation] = True
                elif operation in {"select", "insert", "update"}:
                    if not isinstance(value, list) or not value:
                        raise ValueError("Every grant must enumerate current columns")
                    for column in value:
                        identifier(column)
                    old = dest.get(operation, [])
                    dest[operation] = sorted(set(old + value))
                else:
                    raise ValueError("Unknown privilege")
    # Every dynamic value below has the restrictive identifier validation above.
    lines = ["-- Generated by deploy/postgres/grants.py; no credentials in this plan.",
             "BEGIN;", "SET LOCAL lock_timeout='5s';", "SET LOCAL statement_timeout='30s';",
             f"SET LOCAL search_path={schema_sql},pg_catalog;", f"""DO $grant_preflight$
DECLARE target oid; ns oid; item record;
BEGIN
 SELECT oid INTO STRICT target FROM pg_catalog.pg_roles WHERE rolname='{role}' AND rolcanlogin
  AND NOT (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls OR rolinherit);
 SELECT oid INTO STRICT ns FROM pg_catalog.pg_namespace WHERE nspname='{schema}';
 IF EXISTS(SELECT 1 FROM pg_catalog.pg_auth_members WHERE member=target)
 OR EXISTS(SELECT 1 FROM pg_catalog.pg_database WHERE datdba=target)
 OR EXISTS(SELECT 1 FROM pg_catalog.pg_namespace WHERE nspowner=target)
 OR EXISTS(SELECT 1 FROM pg_catalog.pg_class WHERE relowner=target)
 OR EXISTS(SELECT 1 FROM pg_catalog.pg_proc WHERE proowner=target)
 THEN RAISE EXCEPTION 'runtime role has membership or object ownership'; END IF;
 IF EXISTS(SELECT 1 FROM pg_catalog.pg_class c CROSS JOIN LATERAL pg_catalog.aclexplode(c.relacl) a
  WHERE c.relnamespace=ns AND a.grantee=0)
 OR EXISTS(SELECT 1 FROM pg_catalog.pg_attribute t JOIN pg_catalog.pg_class c ON c.oid=t.attrelid
  CROSS JOIN LATERAL pg_catalog.aclexplode(t.attacl) a WHERE c.relnamespace=ns AND a.grantee=0)
 THEN RAISE EXCEPTION 'schema has public table or column privileges'; END IF;
 IF NOT EXISTS(SELECT 1 FROM {schema_sql}.dashboard_schema_migrations WHERE name='migrations/{manifest['schemaMigration']}')
 THEN RAISE EXCEPTION 'required reviewed migration is absent'; END IF;
 -- Table REVOKE alone does not remove prior column grants.
 FOR item IN SELECT c.relname,string_agg(pg_catalog.quote_ident(a.attname),',' ORDER BY a.attnum) AS columns
  FROM pg_catalog.pg_class c JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid
  WHERE c.relnamespace=ns AND c.relkind IN ('r','p') AND a.attnum>0 AND NOT a.attisdropped GROUP BY c.relname LOOP
  EXECUTE format('REVOKE ALL (%s) ON TABLE %I.%I FROM %I',item.columns,'{schema}',item.relname,'{role}');
 END LOOP;
END;
$grant_preflight$;""",
             f"REVOKE ALL ON ALL TABLES IN SCHEMA {schema_sql} FROM {role_sql};",
             f"REVOKE ALL ON ALL SEQUENCES IN SCHEMA {schema_sql} FROM {role_sql};",
             f"REVOKE ALL ON ALL FUNCTIONS IN SCHEMA {schema_sql} FROM {role_sql};",
             f"REVOKE ALL ON SCHEMA {schema_sql} FROM {role_sql};",
             f"GRANT USAGE ON SCHEMA {schema_sql} TO {role_sql};"]
    for table, grants in sorted(merged.items()):
        for operation, value in sorted(grants.items()):
            columns = "" if value is True else " (" + ",".join(identifier(v) for v in value) + ")"
            lines.append(f"GRANT {operation.upper()}{columns} ON TABLE {schema_sql}.{identifier(table)} TO {role_sql};")
    if "retention" in components:
        lines.append(f"GRANT EXECUTE ON FUNCTION {schema_sql}.dashboard_notification_retention_seconds() TO {role_sql};")
    lines += [f"""DO $grant_postflight$
BEGIN
 IF pg_catalog.has_schema_privilege('{role}','{schema}','CREATE')
 OR pg_catalog.has_database_privilege('{role}',current_database(),'CREATE')
 THEN RAISE EXCEPTION 'runtime role inherits database/schema creation authority'; END IF;
END;
$grant_postflight$;""", "COMMIT;"]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", required=True)
    parser.add_argument("--role", required=True)
    parser.add_argument("--component", action="append", required=True, choices=sorted(COMPONENTS))
    args = parser.parse_args()
    try:
        print(render(args.schema, args.role, args.component), end="")
    except (ValueError, KeyError, TypeError):
        parser.error("Grant plan input or checked-in manifest is invalid")


if __name__ == "__main__":
    main()
