// Generated by scripts/generate-contracts.py; do not edit.
// OpenAPI SHA-256: 6ddf69d0c4d2c700160c16972318dfe6e07ed8e2ac990bf9ea64f39f2c6d438b
// Unknown source enums remain strings. Auth, bounds and runtime validation belong to the injected transport and server.

export interface Account {
  "id": string;
  "displayName": string;
}

export interface Artifact {
  "id": string;
  "name": string;
  "sizeBytes": string;
  "checksum": string;
  "publishedAt": string;
  "availability": string;
  "runId": string;
  "runNumber": string;
  "executionId": string;
  "targetGenerationId": string;
}

export interface ArtifactPage {
  "items": Array<Artifact>;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
  "total": string;
}

export interface Bootstrap {
  "apiVersion": string;
  "account": Account;
  "deployments": Array<Deployment>;
  "preferences": Preferences;
  "limits": Limits;
  "csrfToken"?: string;
  "fixtureMode"?: boolean;
  "completeness": string;
}

export interface Citation {
  "id": string;
  "code": string;
  "label": string;
  "kind": string;
  "sourceEvidenceId"?: string;
  "startOffset"?: string;
  "endOffset"?: string;
  "taskId": string;
  "reportId": string;
  "evidenceId": string;
  "analysisEvidenceId": string;
  "valueJSON"?: string;
  "bytesBase64"?: string;
  "rangeBasis"?: string;
  "originalStartOffset"?: string;
  "originalEndOffset"?: string;
  "originalOffsetsExact": boolean;
  "sourceEntityId"?: string;
  "sourceRevision"?: string;
  "runId"?: string;
  "runNumber"?: string;
  "executionId"?: string;
  "stream"?: string;
  "quality": string;
  "disclosure": string;
  "capturedAt"?: string;
  "observedAt"?: string;
}

export interface CitationRef {
  "id": string;
  "code": string;
  "label": string;
  "kind": string;
  "sourceEvidenceId"?: string;
  "startOffset"?: string;
  "endOffset"?: string;
}

export interface Dependency {
  "upstreamNodeId": string;
  "predicate": string;
  "status": string;
}

export interface Deployment {
  "id": string;
  "name": string;
  "status": string;
  "namespaces": Array<Namespace>;
}

export interface Device {
  "installationId": string;
  "revision": string;
  "label": string;
  "topic": string;
  "environment": string;
  "state": string;
  "enabled": boolean;
  "muted": boolean;
  "permission": string;
  "tokenStatus": string;
  "createdAt": string;
  "updatedAt": string;
  "lastSeenAt": string;
}

export interface DeviceBindInput {
  "installationSecret": string;
  "label": string;
  "topic": string;
  "environment": string;
  "token": string;
  "permission": string;
  "enabled": boolean;
  "muted": boolean;
  "confirmBind": boolean;
}

export interface DevicePage {
  "items": Array<Device>;
}

export interface DeviceSettingsInput {
  "label": string;
  "enabled": boolean;
  "muted": boolean;
}

export interface DeviceSwitchInput {
  "installationSecret": string;
  "label": string;
  "topic": string;
  "environment": string;
  "token": string;
  "permission": string;
  "enabled": boolean;
  "muted": boolean;
  "confirmSwitch": boolean;
}

export interface DeviceTokenInput {
  "installationSecret": string;
  "token": string;
  "permission": string;
}

export interface Error {
  "code": string;
  "message": string;
  "requestId"?: string;
}

export interface Finding {
  "id": string;
  "code": string;
  "category": string;
  "severity": string;
  "title": string;
  "explanation": string;
  "confidence": ReportConfidence;
  "supportingEvidence": Array<string>;
  "contradictingEvidence": Array<string>;
  "contradictingFindings": Array<string>;
  "analyzer": string;
}

export interface GraphEdge {
  "from": string;
  "to": string;
  "fromJobId": string;
  "toJobId": string;
  "predicate": string;
  "outcomes": Array<string>;
  "upstreamPhase": string;
  "upstreamOutcome"?: string;
  "state": string;
}

export interface GraphEdgePage {
  "items": Array<GraphEdge>;
  "total": string;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
}

export interface GraphNeighborhood {
  "centerId": string;
  "nodes": Array<WorkloadChild>;
  "edges": Array<GraphEdge>;
  "totalNodes": string;
  "totalEdges": string;
  "omittedNodes": string;
  "omittedEdges": string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
}

export interface GroupReference {
  "collectionId"?: string;
  "collectionIndex"?: number;
  "graphId"?: string;
  "graphIndex"?: number;
}

export interface InboxItem {
  "id": string;
  "job": JobRef;
  "outcome": string;
  "eventAt": string;
  "createdAt": string;
  "read": boolean;
  "matchedRules": Array<string>;
  "deliveryStatus"?: string;
}

export interface InboxItemPage {
  "items": Array<InboxItem>;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
}

export interface InstallationProofInput {
  "installationSecret": string;
}

export interface InstallationState {
  "installationId": string;
  "revision": string;
  "hasBinding": boolean;
  "boundToCurrentAccount": boolean;
}

export interface Job {
  "deploymentId": string;
  "namespaceId": string;
  "id": string;
  "name"?: string;
  "targetId": string;
  "targetGeneration"?: string;
  "backend"?: string;
  "revision": string;
  "owner"?: Owner;
  "createdAt": string;
  "updatedAt": string;
  "startedAt"?: string;
  "completedAt"?: string;
  "desiredState": string;
  "phase": string;
  "outcome"?: string;
  "confidence": string;
  "labels": Record<string, string>;
  "scheduler"?: Scheduler;
  "disposition"?: string;
  "targetGenerationId"?: string;
  "imported"?: boolean;
  "lifecycle"?: Lifecycle;
  "currentRun"?: RunReference;
  "group"?: GroupReference;
}

export interface JobDetail {
  "job": Job;
  "fetchedAt": string;
}

export interface JobPage {
  "items": Array<Job>;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
}

export interface JobRef {
  "deploymentId": string;
  "namespaceId": string;
  "jobId": string;
}

export interface Lifecycle {
  "startedRecordedAt"?: string;
  "startedProvenance"?: string;
  "completedRecordedAt"?: string;
  "completedProvenance"?: string;
}

export interface Limits {
  "defaultPageSize": number;
  "maxPageSize": number;
  "logReadBytes": number;
  "logBufferBytes": number;
  "graphNodes": number;
  "graphEdges": number;
}

export interface LogRange {
  "bytesBase64": string;
  "executionId": string;
  "stream": string;
  "runId"?: string;
  "startOffset": string;
  "endOffset": string;
  "nextCursor"?: string;
  "state": string;
  "truncated"?: boolean;
  "capturedAt"?: string;
  "runNumber"?: string;
}

export interface Namespace {
  "id": string;
  "name": string;
  "roles": Array<string>;
  "capabilities": Array<string>;
  "authorizationVersion": string;
  "authorizationCheckedAt": string;
  "authorizationExpiresAt": string;
}

export interface Overview {
  "active": number | null;
  "awaitingExecution": number | null;
  "running": number | null;
  "evidenceAttention": number | null;
  "missingCompletionTime": number | null;
  "terminal": Record<string, number | null>;
  "window": Window;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
}

export interface Owner {
  "id": string;
  "displayName"?: string;
  "isCurrentUser": boolean;
}

export interface Preferences {
  "revision": string;
  "timezone": string;
  "appearance": string;
  "refreshSeconds": number;
}

export interface ReadUpdate {
  "read": boolean;
}

export interface Report {
  "deploymentId": string;
  "namespaceId": string;
  "taskId": string;
  "jobId": string;
  "sourceRevision": string;
  "runId"?: string;
  "profile": string;
  "state": string;
  "createdAt": string;
  "expiresAt": string;
  "outdated": boolean;
  "reportId"?: string;
  "evidenceId"?: string;
  "analysisEvidenceId"?: string;
  "failureCode"?: string;
  "detail"?: ReportDetail;
}

export interface ReportAction {
  "id": string;
  "code": string;
  "kind": string;
  "summary": string;
  "description": string;
  "supportingEvidence": Array<string>;
  "requiresConfirmation": boolean;
}

export interface ReportAnalyzer {
  "name": string;
  "version": string;
}

export interface ReportConfidence {
  "score": number;
  "band": string;
  "basis": string;
}

export interface ReportDetail {
  "capturedAt": string;
  "generatedAt": string;
  "controlInstanceId": string;
  "controlVersion": string;
  "contractVersion": string;
  "platform": string;
  "phase": string;
  "outcome"?: string;
  "runs": Array<RunReference>;
  "versions": ReportVersions;
  "mode": string;
  "primaryFindingId": string;
  "analyzers": Array<ReportAnalyzer>;
  "generators": Array<ReportGenerator>;
  "findings": Array<Finding>;
  "actions": Array<ReportAction>;
  "retry": ReportRetry;
  "citations": Array<CitationRef>;
  "missingEvidence": Array<ReportMissingEvidence>;
  "warnings": Array<ReportWarning>;
  "disclosure": ReportDisclosure;
  "omissions": Array<ReportOmission>;
  "redactionNotices": Array<ReportRedaction>;
}

export interface ReportDisclosure {
  "providerInvoked": boolean;
  "generatedContentUsed": boolean;
  "locality": string;
  "profile"?: string;
  "provider"?: string;
  "model"?: string;
  "requestId"?: string;
  "classes": Array<string>;
  "itemIds": Array<string>;
  "artifactIds": Array<string>;
  "enrichmentIds": Array<string>;
  "itemCount": string;
  "artifactCount": string;
  "enrichmentCount": string;
  "artifactBytes": string;
  "enrichmentBytes": string;
  "requestBytes": string;
  "redactionNoticeCount": string;
}

export interface ReportGenerator {
  "provider": string;
  "model": string;
  "profile": string;
  "locality": string;
}

export interface ReportMissingEvidence {
  "code": string;
  "description": string;
}

export interface ReportOmission {
  "code": string;
  "affects": Array<string>;
}

export interface ReportPage {
  "items": Array<Report>;
  "nextCursor"?: string;
  "fetchedAt": string;
}

export interface ReportRedaction {
  "code": string;
  "affects": Array<string>;
  "count": string;
}

export interface ReportRequest {
  "profile": string;
  "runId"?: string;
}

export interface ReportRetry {
  "verdict": string;
  "existingPolicy": string;
  "confidence": ReportConfidence;
  "rationale": string;
  "reasons": Array<string>;
  "supportingEvidence": Array<string>;
  "earliestAt"?: string;
}

export interface ReportVersions {
  "companion": string;
  "engine": string;
  "jobman": string;
  "collector": string;
  "evidenceSchema": number;
  "reportSchema": number;
  "generationSchema": number;
  "proposalSchema": number;
}

export interface ReportWarning {
  "code": string;
  "message": string;
}

export interface Rule {
  "id": string;
  "revision": string;
  "name": string;
  "enabled": boolean;
  "scope": string;
  "outcomeMode": string;
  "outcomes": Array<string>;
  "scopes": Array<RuleScope>;
  "jobs": Array<JobRef>;
  "inaccessibleScopes": number;
  "unavailableScopes": number;
  "createdAt": string;
  "updatedAt": string;
}

export interface RuleEnabledInput {
  "enabled": boolean;
}

export interface RuleInput {
  "name": string;
  "enabled": boolean;
  "scope": string;
  "namespaces": Array<Scope>;
  "jobs": Array<JobRef>;
  "outcomeMode": string;
  "outcomes": Array<string>;
}

export interface RulePage {
  "items": Array<Rule>;
  "nextCursor"?: string;
}

export interface RuleScope {
  "deploymentId": string;
  "namespaceId": string;
  "status": string;
  "activatedAt"?: string;
}

export interface RunReference {
  "id": string;
  "number": string;
  "executionId"?: string;
}

export interface Scheduler {
  "state"?: string;
  "jobId"?: string;
  "observedAt"?: string;
  "reason"?: string;
  "cluster"?: string;
}

export interface Scope {
  "deploymentId": string;
  "namespaceId": string;
}

export interface SourceStatus {
  "deploymentId": string;
  "namespaceId": string;
  "status": string;
  "asOf"?: string;
  "fetchedAt": string;
  "message"?: string;
}

export interface Target {
  "deploymentId": string;
  "namespaceId": string;
  "targetId": string;
  "name": string;
  "kind": string;
  "state": string;
  "revision": string;
  "createdAt": string;
  "updatedAt": string;
  "asOf": string;
  "generation": TargetGeneration;
}

export interface TargetDetail {
  "target": Target;
  "sources": Array<SourceStatus>;
  "completeness": string;
  "fetchedAt": string;
}

export interface TargetGeneration {
  "id": string;
  "number": string;
  "executionBackend": string;
  "transport": string;
  "runtimes": Array<string>;
  "operatingSystems": Array<string>;
  "architectures": Array<string>;
  "capabilities": Array<string>;
  "partitions": Array<TargetPartition>;
  "partitionCount": string;
  "partitionsTruncated": boolean;
  "logStore"?: TargetStore;
  "artifactStores": Array<TargetStore>;
  "provider": TargetProvider;
}

export interface TargetPage {
  "items": Array<Target>;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
  "total": string;
  "totals": Array<TargetTotal>;
}

export interface TargetPartition {
  "name": string;
  "isDefault": boolean;
}

export interface TargetPartitionPage {
  "items": Array<TargetPartition>;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
  "total": string;
  "targetId": string;
  "generationId": string;
}

export interface TargetProvider {
  "kind": string;
  "region"?: string;
  "clusterName"?: string;
}

export interface TargetStore {
  "name": string;
  "version": string;
}

export interface TargetTotal {
  "deploymentId": string;
  "namespaceId": string;
  "total": string;
  "asOf": string;
}

export interface Window {
  "from": string;
  "to": string;
}

export interface Workload {
  "deploymentId": string;
  "namespaceId": string;
  "id": string;
  "name"?: string;
  "kind": string;
  "createdAt": string;
  "totalChildren": string;
  "counts": Record<string, string>;
  "concurrency"?: string;
  "failurePolicy"?: string;
  "arrayId"?: string;
  "revision": string;
  "updatedAt"?: string;
  "asOf": string;
  "phase"?: string;
  "outcome"?: string;
  "arrayMode"?: string;
  "unsatisfiedPolicy"?: string;
  "arrayPolicy"?: string;
}

export interface WorkloadChild {
  "id": string;
  "job": Job;
  "readiness"?: string;
  "disposition"?: string;
  "taskIndex"?: string;
  "dependencies"?: Array<Dependency>;
  "name"?: string;
  "index": string;
  "dependencyCounts"?: Record<string, string>;
}

export interface WorkloadChildrenPage {
  "items": Array<WorkloadChild>;
  "total": string;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
}

export interface WorkloadDetail {
  "workload": Workload;
  "children": Array<WorkloadChild>;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
  "omittedNodes"?: string;
  "omittedEdges"?: string;
  "total": string;
}

export interface WorkloadPage {
  "items": Array<Workload>;
  "nextCursor"?: string;
  "completeness": string;
  "sources": Array<SourceStatus>;
  "fetchedAt": string;
  "total": string;
  "totals": Array<WorkloadTotal>;
}

export interface WorkloadTotal {
  "deploymentId": string;
  "namespaceId": string;
  "total": string;
  "asOf": string;
}

export interface DashboardRequest {
  method: string;
  path: string;
  query?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string | undefined>;
  body?: unknown;
  signal?: AbortSignal;
}
export type DashboardTransport = <T>(request: DashboardRequest) => Promise<T>;

export interface BootstrapParameters {
  signal?: AbortSignal;
}

export interface JobParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "jobId": string;
  };
  signal?: AbortSignal;
}

export interface ArtifactsParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "jobId": string;
  };
  query?: {
    "cursor"?: string;
    "limit"?: number;
    "runNumber"?: string;
  };
  signal?: AbortSignal;
}

export interface LogsParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "jobId": string;
  };
  query?: {
    "cursor"?: string;
    "stream"?: string;
    "limitBytes"?: number;
    "runNumber"?: string;
  };
  signal?: AbortSignal;
}

export interface ReportsParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "jobId": string;
  };
  query?: {
    "cursor"?: string;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export interface RequestReportParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "jobId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "Idempotency-Key": string;
  };
  body: ReportRequest;
  signal?: AbortSignal;
}

export interface ReportParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "jobId": string;
    "taskId": string;
  };
  signal?: AbortSignal;
}

export interface CitationParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "jobId": string;
    "taskId": string;
    "citationId": string;
  };
  signal?: AbortSignal;
}

export interface TargetParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "targetId": string;
  };
  signal?: AbortSignal;
}

export interface TargetPartitionsParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "targetId": string;
  };
  query: {
    "generationId": string;
    "cursor"?: string;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export interface GraphEdgesParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "workloadId": string;
  };
  query?: {
    "cursor"?: string;
    "limit"?: number;
    "nodeId"?: string;
    "direction"?: string;
  };
  signal?: AbortSignal;
}

export interface GraphNeighborhoodParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "workloadId": string;
  };
  query: {
    "nodeId": string;
    "maxNodes"?: number;
    "maxEdges"?: number;
  };
  signal?: AbortSignal;
}

export interface WorkloadParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "kind": string;
    "workloadId": string;
  };
  query?: {
    "cursor"?: string;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export interface WorkloadChildrenParameters {
  path: {
    "deploymentId": string;
    "namespaceId": string;
    "kind": string;
    "workloadId": string;
  };
  query?: {
    "cursor"?: string;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export interface DevicesParameters {
  signal?: AbortSignal;
}

export interface RemoveDeviceParameters {
  path: {
    "installationId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  signal?: AbortSignal;
}

export interface BindDeviceParameters {
  path: {
    "installationId": string;
  };
  headers?: {
    "X-CSRF-Token"?: string;
    "If-Match"?: string;
    "If-None-Match"?: string;
  };
  body: DeviceBindInput;
  signal?: AbortSignal;
}

export interface DetachInstallationParameters {
  path: {
    "installationId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  body: InstallationProofInput;
  signal?: AbortSignal;
}

export interface InspectInstallationParameters {
  path: {
    "installationId": string;
  };
  headers?: {
    "X-CSRF-Token"?: string;
  };
  body: InstallationProofInput;
  signal?: AbortSignal;
}

export interface UpdateDeviceSettingsParameters {
  path: {
    "installationId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  body: DeviceSettingsInput;
  signal?: AbortSignal;
}

export interface SwitchDeviceBindingParameters {
  path: {
    "installationId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  body: DeviceSwitchInput;
  signal?: AbortSignal;
}

export interface RefreshDeviceTokenParameters {
  path: {
    "installationId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  body: DeviceTokenInput;
  signal?: AbortSignal;
}

export interface InboxParameters {
  query?: {
    "cursor"?: string;
    "limit"?: number;
    "unread"?: boolean;
  };
  signal?: AbortSignal;
}

export interface UpdateInboxParameters {
  path: {
    "inboxId": string;
  };
  headers?: {
    "X-CSRF-Token"?: string;
  };
  body: ReadUpdate;
  signal?: AbortSignal;
}

export interface JobsParameters {
  query?: {
    "scope"?: string;
    "cursor"?: string;
    "phase"?: string;
    "outcome"?: string;
    "owner"?: string;
    "jobId"?: string;
    "from"?: string;
    "to"?: string;
    "completedFrom"?: string;
    "completedTo"?: string;
    "attention"?: boolean;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export interface OverviewParameters {
  query?: {
    "scope"?: string;
    "from"?: string;
    "to"?: string;
    "completedFrom"?: string;
    "completedTo"?: string;
    "windowHours"?: number;
  };
  signal?: AbortSignal;
}

export interface UpdatePreferencesParameters {
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  body: Preferences;
  signal?: AbortSignal;
}

export interface RulesParameters {
  query?: {
    "cursor"?: string;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export interface CreateRuleParameters {
  headers?: {
    "X-CSRF-Token"?: string;
  };
  body: RuleInput;
  signal?: AbortSignal;
}

export interface DeleteRuleParameters {
  path: {
    "ruleId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  signal?: AbortSignal;
}

export interface RuleParameters {
  path: {
    "ruleId": string;
  };
  signal?: AbortSignal;
}

export interface UpdateRuleParameters {
  path: {
    "ruleId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  body: RuleInput;
  signal?: AbortSignal;
}

export interface SetRuleEnabledParameters {
  path: {
    "ruleId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  body: RuleEnabledInput;
  signal?: AbortSignal;
}

export interface RevalidateRuleParameters {
  path: {
    "ruleId": string;
  };
  headers: {
    "X-CSRF-Token"?: string;
    "If-Match": string;
  };
  signal?: AbortSignal;
}

export interface TargetsParameters {
  query?: {
    "scope"?: string;
    "cursor"?: string;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export interface WorkloadsParameters {
  path: {
    "kind": string;
  };
  query?: {
    "scope"?: string;
    "cursor"?: string;
    "limit"?: number;
  };
  signal?: AbortSignal;
}

export class DashboardClient {
  constructor(private readonly transport: DashboardTransport) {}
  bootstrap(parameters: BootstrapParameters = {}): Promise<Bootstrap> {
    return this.transport<Bootstrap>({ method: "GET", path: `/api/v1/bootstrap`, signal: parameters.signal });
  }
  job(parameters: JobParameters): Promise<JobDetail> {
    return this.transport<JobDetail>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/jobs/${encodeURIComponent(String(parameters.path["jobId"]))}`, signal: parameters.signal });
  }
  artifacts(parameters: ArtifactsParameters): Promise<ArtifactPage> {
    return this.transport<ArtifactPage>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/jobs/${encodeURIComponent(String(parameters.path["jobId"]))}/artifacts`, signal: parameters.signal, query: parameters.query });
  }
  logs(parameters: LogsParameters): Promise<LogRange> {
    return this.transport<LogRange>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/jobs/${encodeURIComponent(String(parameters.path["jobId"]))}/logs`, signal: parameters.signal, query: parameters.query });
  }
  reports(parameters: ReportsParameters): Promise<ReportPage> {
    return this.transport<ReportPage>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/jobs/${encodeURIComponent(String(parameters.path["jobId"]))}/reports`, signal: parameters.signal, query: parameters.query });
  }
  requestReport(parameters: RequestReportParameters): Promise<Report> {
    return this.transport<Report>({ method: "POST", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/jobs/${encodeURIComponent(String(parameters.path["jobId"]))}/reports`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  report(parameters: ReportParameters): Promise<Report> {
    return this.transport<Report>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/jobs/${encodeURIComponent(String(parameters.path["jobId"]))}/reports/${encodeURIComponent(String(parameters.path["taskId"]))}`, signal: parameters.signal });
  }
  citation(parameters: CitationParameters): Promise<Citation> {
    return this.transport<Citation>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/jobs/${encodeURIComponent(String(parameters.path["jobId"]))}/reports/${encodeURIComponent(String(parameters.path["taskId"]))}/citations/${encodeURIComponent(String(parameters.path["citationId"]))}`, signal: parameters.signal });
  }
  target(parameters: TargetParameters): Promise<TargetDetail> {
    return this.transport<TargetDetail>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/targets/${encodeURIComponent(String(parameters.path["targetId"]))}`, signal: parameters.signal });
  }
  targetPartitions(parameters: TargetPartitionsParameters): Promise<TargetPartitionPage> {
    return this.transport<TargetPartitionPage>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/targets/${encodeURIComponent(String(parameters.path["targetId"]))}/partitions`, signal: parameters.signal, query: parameters.query });
  }
  graphEdges(parameters: GraphEdgesParameters): Promise<GraphEdgePage> {
    return this.transport<GraphEdgePage>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/workloads/graph/${encodeURIComponent(String(parameters.path["workloadId"]))}/dependencies`, signal: parameters.signal, query: parameters.query });
  }
  graphNeighborhood(parameters: GraphNeighborhoodParameters): Promise<GraphNeighborhood> {
    return this.transport<GraphNeighborhood>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/workloads/graph/${encodeURIComponent(String(parameters.path["workloadId"]))}/neighborhood`, signal: parameters.signal, query: parameters.query });
  }
  workload(parameters: WorkloadParameters): Promise<WorkloadDetail> {
    return this.transport<WorkloadDetail>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/workloads/${encodeURIComponent(String(parameters.path["kind"]))}/${encodeURIComponent(String(parameters.path["workloadId"]))}`, signal: parameters.signal, query: parameters.query });
  }
  workloadChildren(parameters: WorkloadChildrenParameters): Promise<WorkloadChildrenPage> {
    return this.transport<WorkloadChildrenPage>({ method: "GET", path: `/api/v1/deployments/${encodeURIComponent(String(parameters.path["deploymentId"]))}/namespaces/${encodeURIComponent(String(parameters.path["namespaceId"]))}/workloads/${encodeURIComponent(String(parameters.path["kind"]))}/${encodeURIComponent(String(parameters.path["workloadId"]))}/children`, signal: parameters.signal, query: parameters.query });
  }
  devices(parameters: DevicesParameters = {}): Promise<DevicePage> {
    return this.transport<DevicePage>({ method: "GET", path: `/api/v1/devices`, signal: parameters.signal });
  }
  removeDevice(parameters: RemoveDeviceParameters): Promise<void> {
    return this.transport<void>({ method: "DELETE", path: `/api/v1/devices/${encodeURIComponent(String(parameters.path["installationId"]))}`, signal: parameters.signal, headers: parameters.headers });
  }
  bindDevice(parameters: BindDeviceParameters): Promise<Device> {
    return this.transport<Device>({ method: "POST", path: `/api/v1/devices/${encodeURIComponent(String(parameters.path["installationId"]))}/bind`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  detachInstallation(parameters: DetachInstallationParameters): Promise<void> {
    return this.transport<void>({ method: "POST", path: `/api/v1/devices/${encodeURIComponent(String(parameters.path["installationId"]))}/detach`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  inspectInstallation(parameters: InspectInstallationParameters): Promise<InstallationState> {
    return this.transport<InstallationState>({ method: "POST", path: `/api/v1/devices/${encodeURIComponent(String(parameters.path["installationId"]))}/inspect`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  updateDeviceSettings(parameters: UpdateDeviceSettingsParameters): Promise<Device> {
    return this.transport<Device>({ method: "PUT", path: `/api/v1/devices/${encodeURIComponent(String(parameters.path["installationId"]))}/settings`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  switchDeviceBinding(parameters: SwitchDeviceBindingParameters): Promise<Device> {
    return this.transport<Device>({ method: "POST", path: `/api/v1/devices/${encodeURIComponent(String(parameters.path["installationId"]))}/switch`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  refreshDeviceToken(parameters: RefreshDeviceTokenParameters): Promise<Device> {
    return this.transport<Device>({ method: "PUT", path: `/api/v1/devices/${encodeURIComponent(String(parameters.path["installationId"]))}/token`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  inbox(parameters: InboxParameters = {}): Promise<InboxItemPage> {
    return this.transport<InboxItemPage>({ method: "GET", path: `/api/v1/inbox`, signal: parameters.signal, query: parameters.query });
  }
  updateInbox(parameters: UpdateInboxParameters): Promise<InboxItem> {
    return this.transport<InboxItem>({ method: "PATCH", path: `/api/v1/inbox/${encodeURIComponent(String(parameters.path["inboxId"]))}`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  jobs(parameters: JobsParameters = {}): Promise<JobPage> {
    return this.transport<JobPage>({ method: "GET", path: `/api/v1/jobs`, signal: parameters.signal, query: parameters.query });
  }
  overview(parameters: OverviewParameters = {}): Promise<Overview> {
    return this.transport<Overview>({ method: "GET", path: `/api/v1/overview`, signal: parameters.signal, query: parameters.query });
  }
  updatePreferences(parameters: UpdatePreferencesParameters): Promise<Preferences> {
    return this.transport<Preferences>({ method: "PUT", path: `/api/v1/preferences`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  rules(parameters: RulesParameters = {}): Promise<RulePage> {
    return this.transport<RulePage>({ method: "GET", path: `/api/v1/rules`, signal: parameters.signal, query: parameters.query });
  }
  createRule(parameters: CreateRuleParameters): Promise<Rule> {
    return this.transport<Rule>({ method: "POST", path: `/api/v1/rules`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  deleteRule(parameters: DeleteRuleParameters): Promise<void> {
    return this.transport<void>({ method: "DELETE", path: `/api/v1/rules/${encodeURIComponent(String(parameters.path["ruleId"]))}`, signal: parameters.signal, headers: parameters.headers });
  }
  rule(parameters: RuleParameters): Promise<Rule> {
    return this.transport<Rule>({ method: "GET", path: `/api/v1/rules/${encodeURIComponent(String(parameters.path["ruleId"]))}`, signal: parameters.signal });
  }
  updateRule(parameters: UpdateRuleParameters): Promise<Rule> {
    return this.transport<Rule>({ method: "PUT", path: `/api/v1/rules/${encodeURIComponent(String(parameters.path["ruleId"]))}`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  setRuleEnabled(parameters: SetRuleEnabledParameters): Promise<Rule> {
    return this.transport<Rule>({ method: "PUT", path: `/api/v1/rules/${encodeURIComponent(String(parameters.path["ruleId"]))}/enabled`, signal: parameters.signal, headers: parameters.headers, body: parameters.body });
  }
  revalidateRule(parameters: RevalidateRuleParameters): Promise<Rule> {
    return this.transport<Rule>({ method: "POST", path: `/api/v1/rules/${encodeURIComponent(String(parameters.path["ruleId"]))}/revalidate`, signal: parameters.signal, headers: parameters.headers });
  }
  targets(parameters: TargetsParameters = {}): Promise<TargetPage> {
    return this.transport<TargetPage>({ method: "GET", path: `/api/v1/targets`, signal: parameters.signal, query: parameters.query });
  }
  workloads(parameters: WorkloadsParameters): Promise<WorkloadPage> {
    return this.transport<WorkloadPage>({ method: "GET", path: `/api/v1/workloads/${encodeURIComponent(String(parameters.path["kind"]))}`, signal: parameters.signal, query: parameters.query });
  }
}
