// Generated by scripts/generate-contracts.py; do not edit.
// OpenAPI SHA-256: f475a91dc30bbd369d310e9077700c2a6af63d616c0ef3518f552f4db1aae33e
// Dates and wide integers retain their wire strings; unknown enums remain strings.
import Foundation

public enum DashboardAPI {
  public struct Account: Codable, Sendable {
    public var `id`: String
    public var `displayName`: String
    public init(id: String, displayName: String) {
      self.`id` = `id`
      self.`displayName` = `displayName`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `displayName`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`displayName` = try container.decode(String.self, forKey: .`displayName`)
    }
  }

  public struct Artifact: Codable, Sendable {
    public var `id`: String
    public var `name`: String
    public var `sizeBytes`: String
    public var `checksum`: String?
    public var `publishedAt`: String?
    public var `availability`: String
    public init(id: String, name: String, sizeBytes: String, checksum: String? = nil, publishedAt: String? = nil, availability: String) {
      self.`id` = `id`
      self.`name` = `name`
      self.`sizeBytes` = `sizeBytes`
      self.`checksum` = `checksum`
      self.`publishedAt` = `publishedAt`
      self.`availability` = `availability`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `name`
      case `sizeBytes`
      case `checksum`
      case `publishedAt`
      case `availability`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`name` = try container.decode(String.self, forKey: .`name`)
      self.`sizeBytes` = try container.decode(String.self, forKey: .`sizeBytes`)
      self.`checksum` = try container.decodeIfPresent(String.self, forKey: .`checksum`)
      self.`publishedAt` = try container.decodeIfPresent(String.self, forKey: .`publishedAt`)
      self.`availability` = try container.decode(String.self, forKey: .`availability`)
    }
  }

  public struct ArtifactPage: Codable, Sendable {
    public var `items`: [DashboardAPI.Artifact]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.Artifact], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.Artifact].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct Bootstrap: Codable, Sendable {
    public var `apiVersion`: String
    public var `account`: DashboardAPI.Account
    public var `deployments`: [DashboardAPI.Deployment]
    public var `preferences`: DashboardAPI.Preferences
    public var `limits`: DashboardAPI.Limits
    public var `csrfToken`: String?
    public var `fixtureMode`: Bool?
    public var `completeness`: String
    public init(apiVersion: String, account: DashboardAPI.Account, deployments: [DashboardAPI.Deployment], preferences: DashboardAPI.Preferences, limits: DashboardAPI.Limits, csrfToken: String? = nil, fixtureMode: Bool? = nil, completeness: String) {
      self.`apiVersion` = `apiVersion`
      self.`account` = `account`
      self.`deployments` = `deployments`
      self.`preferences` = `preferences`
      self.`limits` = `limits`
      self.`csrfToken` = `csrfToken`
      self.`fixtureMode` = `fixtureMode`
      self.`completeness` = `completeness`
    }
    private enum CodingKeys: String, CodingKey {
      case `apiVersion`
      case `account`
      case `deployments`
      case `preferences`
      case `limits`
      case `csrfToken`
      case `fixtureMode`
      case `completeness`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`apiVersion` = try container.decode(String.self, forKey: .`apiVersion`)
      self.`account` = try container.decode(DashboardAPI.Account.self, forKey: .`account`)
      self.`deployments` = try container.decode([DashboardAPI.Deployment].self, forKey: .`deployments`)
      self.`preferences` = try container.decode(DashboardAPI.Preferences.self, forKey: .`preferences`)
      self.`limits` = try container.decode(DashboardAPI.Limits.self, forKey: .`limits`)
      self.`csrfToken` = try container.decodeIfPresent(String.self, forKey: .`csrfToken`)
      self.`fixtureMode` = try container.decodeIfPresent(Bool.self, forKey: .`fixtureMode`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
    }
  }

  public struct Citation: Codable, Sendable {
    public var `id`: String
    public var `label`: String
    public var `text`: String
    public var `startOffset`: String?
    public var `endOffset`: String?
    public init(id: String, label: String, text: String, startOffset: String? = nil, endOffset: String? = nil) {
      self.`id` = `id`
      self.`label` = `label`
      self.`text` = `text`
      self.`startOffset` = `startOffset`
      self.`endOffset` = `endOffset`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `label`
      case `text`
      case `startOffset`
      case `endOffset`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`label` = try container.decode(String.self, forKey: .`label`)
      self.`text` = try container.decode(String.self, forKey: .`text`)
      self.`startOffset` = try container.decodeIfPresent(String.self, forKey: .`startOffset`)
      self.`endOffset` = try container.decodeIfPresent(String.self, forKey: .`endOffset`)
    }
  }

  public struct CitationRef: Codable, Sendable {
    public var `id`: String
    public var `label`: String
    public init(id: String, label: String) {
      self.`id` = `id`
      self.`label` = `label`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `label`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`label` = try container.decode(String.self, forKey: .`label`)
    }
  }

  public struct Dependency: Codable, Sendable {
    public var `upstreamNodeId`: String
    public var `predicate`: String
    public var `status`: String
    public init(upstreamNodeId: String, predicate: String, status: String) {
      self.`upstreamNodeId` = `upstreamNodeId`
      self.`predicate` = `predicate`
      self.`status` = `status`
    }
    private enum CodingKeys: String, CodingKey {
      case `upstreamNodeId`
      case `predicate`
      case `status`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`upstreamNodeId` = try container.decode(String.self, forKey: .`upstreamNodeId`)
      self.`predicate` = try container.decode(String.self, forKey: .`predicate`)
      self.`status` = try container.decode(String.self, forKey: .`status`)
    }
  }

  public struct Deployment: Codable, Sendable {
    public var `id`: String
    public var `name`: String
    public var `status`: String
    public var `namespaces`: [DashboardAPI.Namespace]
    public init(id: String, name: String, status: String, namespaces: [DashboardAPI.Namespace]) {
      self.`id` = `id`
      self.`name` = `name`
      self.`status` = `status`
      self.`namespaces` = `namespaces`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `name`
      case `status`
      case `namespaces`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`name` = try container.decode(String.self, forKey: .`name`)
      self.`status` = try container.decode(String.self, forKey: .`status`)
      self.`namespaces` = try container.decode([DashboardAPI.Namespace].self, forKey: .`namespaces`)
    }
  }

  public struct Device: Codable, Sendable {
    public var `id`: String
    public var `name`: String
    public var `platform`: String?
    public var `enabled`: Bool
    public var `permission`: String?
    public var `lastSeenAt`: String?
    public init(id: String, name: String, platform: String? = nil, enabled: Bool, permission: String? = nil, lastSeenAt: String? = nil) {
      self.`id` = `id`
      self.`name` = `name`
      self.`platform` = `platform`
      self.`enabled` = `enabled`
      self.`permission` = `permission`
      self.`lastSeenAt` = `lastSeenAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `name`
      case `platform`
      case `enabled`
      case `permission`
      case `lastSeenAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`name` = try container.decode(String.self, forKey: .`name`)
      self.`platform` = try container.decodeIfPresent(String.self, forKey: .`platform`)
      self.`enabled` = try container.decode(Bool.self, forKey: .`enabled`)
      self.`permission` = try container.decodeIfPresent(String.self, forKey: .`permission`)
      self.`lastSeenAt` = try container.decodeIfPresent(String.self, forKey: .`lastSeenAt`)
    }
  }

  public struct DevicePage: Codable, Sendable {
    public var `items`: [DashboardAPI.Device]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.Device], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.Device].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct DeviceUpdate: Codable, Sendable {
    public var `enabled`: Bool
    public init(enabled: Bool) {
      self.`enabled` = `enabled`
    }
    private enum CodingKeys: String, CodingKey {
      case `enabled`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`enabled` = try container.decode(Bool.self, forKey: .`enabled`)
    }
  }

  public struct Error: Codable, Sendable {
    public var `code`: String
    public var `message`: String
    public var `requestId`: String?
    public init(code: String, message: String, requestId: String? = nil) {
      self.`code` = `code`
      self.`message` = `message`
      self.`requestId` = `requestId`
    }
    private enum CodingKeys: String, CodingKey {
      case `code`
      case `message`
      case `requestId`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`code` = try container.decode(String.self, forKey: .`code`)
      self.`message` = try container.decode(String.self, forKey: .`message`)
      self.`requestId` = try container.decodeIfPresent(String.self, forKey: .`requestId`)
    }
  }

  public struct Finding: Codable, Sendable {
    public var `id`: String
    public var `severity`: String
    public var `title`: String
    public var `explanation`: String
    public var `confidence`: Double?
    public var `confidenceBasis`: String?
    public var `citations`: [DashboardAPI.CitationRef]
    public var `suggestions`: [String]?
    public var `generated`: Bool?
    public init(id: String, severity: String, title: String, explanation: String, confidence: Double? = nil, confidenceBasis: String? = nil, citations: [DashboardAPI.CitationRef], suggestions: [String]? = nil, generated: Bool? = nil) {
      self.`id` = `id`
      self.`severity` = `severity`
      self.`title` = `title`
      self.`explanation` = `explanation`
      self.`confidence` = `confidence`
      self.`confidenceBasis` = `confidenceBasis`
      self.`citations` = `citations`
      self.`suggestions` = `suggestions`
      self.`generated` = `generated`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `severity`
      case `title`
      case `explanation`
      case `confidence`
      case `confidenceBasis`
      case `citations`
      case `suggestions`
      case `generated`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`severity` = try container.decode(String.self, forKey: .`severity`)
      self.`title` = try container.decode(String.self, forKey: .`title`)
      self.`explanation` = try container.decode(String.self, forKey: .`explanation`)
      self.`confidence` = try container.decodeIfPresent(Double.self, forKey: .`confidence`)
      self.`confidenceBasis` = try container.decodeIfPresent(String.self, forKey: .`confidenceBasis`)
      self.`citations` = try container.decode([DashboardAPI.CitationRef].self, forKey: .`citations`)
      self.`suggestions` = try container.decodeIfPresent([String].self, forKey: .`suggestions`)
      self.`generated` = try container.decodeIfPresent(Bool.self, forKey: .`generated`)
    }
  }

  public struct GroupReference: Codable, Sendable {
    public var `collectionId`: String?
    public var `collectionIndex`: Int64?
    public var `graphId`: String?
    public var `graphIndex`: Int64?
    public init(collectionId: String? = nil, collectionIndex: Int64? = nil, graphId: String? = nil, graphIndex: Int64? = nil) {
      self.`collectionId` = `collectionId`
      self.`collectionIndex` = `collectionIndex`
      self.`graphId` = `graphId`
      self.`graphIndex` = `graphIndex`
    }
    private enum CodingKeys: String, CodingKey {
      case `collectionId`
      case `collectionIndex`
      case `graphId`
      case `graphIndex`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`collectionId` = try container.decodeIfPresent(String.self, forKey: .`collectionId`)
      self.`collectionIndex` = try container.decodeIfPresent(Int64.self, forKey: .`collectionIndex`)
      self.`graphId` = try container.decodeIfPresent(String.self, forKey: .`graphId`)
      self.`graphIndex` = try container.decodeIfPresent(Int64.self, forKey: .`graphIndex`)
    }
  }

  public struct InboxItem: Codable, Sendable {
    public var `id`: String
    public var `job`: DashboardAPI.JobRef
    public var `outcome`: String
    public var `eventAt`: String
    public var `createdAt`: String
    public var `read`: Bool
    public var `matchedRules`: [String]
    public var `deliveryStatus`: String?
    public init(id: String, job: DashboardAPI.JobRef, outcome: String, eventAt: String, createdAt: String, read: Bool, matchedRules: [String], deliveryStatus: String? = nil) {
      self.`id` = `id`
      self.`job` = `job`
      self.`outcome` = `outcome`
      self.`eventAt` = `eventAt`
      self.`createdAt` = `createdAt`
      self.`read` = `read`
      self.`matchedRules` = `matchedRules`
      self.`deliveryStatus` = `deliveryStatus`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `job`
      case `outcome`
      case `eventAt`
      case `createdAt`
      case `read`
      case `matchedRules`
      case `deliveryStatus`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`job` = try container.decode(DashboardAPI.JobRef.self, forKey: .`job`)
      self.`outcome` = try container.decode(String.self, forKey: .`outcome`)
      self.`eventAt` = try container.decode(String.self, forKey: .`eventAt`)
      self.`createdAt` = try container.decode(String.self, forKey: .`createdAt`)
      self.`read` = try container.decode(Bool.self, forKey: .`read`)
      self.`matchedRules` = try container.decode([String].self, forKey: .`matchedRules`)
      self.`deliveryStatus` = try container.decodeIfPresent(String.self, forKey: .`deliveryStatus`)
    }
  }

  public struct InboxItemPage: Codable, Sendable {
    public var `items`: [DashboardAPI.InboxItem]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.InboxItem], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.InboxItem].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct Job: Codable, Sendable {
    public var `deploymentId`: String
    public var `namespaceId`: String
    public var `id`: String
    public var `name`: String?
    public var `targetId`: String
    public var `targetGeneration`: String?
    public var `backend`: String?
    public var `revision`: String
    public var `owner`: DashboardAPI.Owner?
    public var `createdAt`: String
    public var `updatedAt`: String
    public var `startedAt`: String?
    public var `completedAt`: String?
    public var `desiredState`: String
    public var `phase`: String
    public var `outcome`: String?
    public var `confidence`: String
    public var `labels`: [String: String]
    public var `scheduler`: DashboardAPI.Scheduler?
    public var `disposition`: String?
    public var `targetGenerationId`: String?
    public var `imported`: Bool?
    public var `lifecycle`: DashboardAPI.Lifecycle?
    public var `currentRun`: DashboardAPI.RunReference?
    public var `group`: DashboardAPI.GroupReference?
    public init(deploymentId: String, namespaceId: String, id: String, name: String? = nil, targetId: String, targetGeneration: String? = nil, backend: String? = nil, revision: String, owner: DashboardAPI.Owner? = nil, createdAt: String, updatedAt: String, startedAt: String? = nil, completedAt: String? = nil, desiredState: String, phase: String, outcome: String? = nil, confidence: String, labels: [String: String], scheduler: DashboardAPI.Scheduler? = nil, disposition: String? = nil, targetGenerationId: String? = nil, imported: Bool? = nil, lifecycle: DashboardAPI.Lifecycle? = nil, currentRun: DashboardAPI.RunReference? = nil, group: DashboardAPI.GroupReference? = nil) {
      self.`deploymentId` = `deploymentId`
      self.`namespaceId` = `namespaceId`
      self.`id` = `id`
      self.`name` = `name`
      self.`targetId` = `targetId`
      self.`targetGeneration` = `targetGeneration`
      self.`backend` = `backend`
      self.`revision` = `revision`
      self.`owner` = `owner`
      self.`createdAt` = `createdAt`
      self.`updatedAt` = `updatedAt`
      self.`startedAt` = `startedAt`
      self.`completedAt` = `completedAt`
      self.`desiredState` = `desiredState`
      self.`phase` = `phase`
      self.`outcome` = `outcome`
      self.`confidence` = `confidence`
      self.`labels` = `labels`
      self.`scheduler` = `scheduler`
      self.`disposition` = `disposition`
      self.`targetGenerationId` = `targetGenerationId`
      self.`imported` = `imported`
      self.`lifecycle` = `lifecycle`
      self.`currentRun` = `currentRun`
      self.`group` = `group`
    }
    private enum CodingKeys: String, CodingKey {
      case `deploymentId`
      case `namespaceId`
      case `id`
      case `name`
      case `targetId`
      case `targetGeneration`
      case `backend`
      case `revision`
      case `owner`
      case `createdAt`
      case `updatedAt`
      case `startedAt`
      case `completedAt`
      case `desiredState`
      case `phase`
      case `outcome`
      case `confidence`
      case `labels`
      case `scheduler`
      case `disposition`
      case `targetGenerationId`
      case `imported`
      case `lifecycle`
      case `currentRun`
      case `group`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`deploymentId` = try container.decode(String.self, forKey: .`deploymentId`)
      self.`namespaceId` = try container.decode(String.self, forKey: .`namespaceId`)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`name` = try container.decodeIfPresent(String.self, forKey: .`name`)
      self.`targetId` = try container.decode(String.self, forKey: .`targetId`)
      self.`targetGeneration` = try container.decodeIfPresent(String.self, forKey: .`targetGeneration`)
      self.`backend` = try container.decodeIfPresent(String.self, forKey: .`backend`)
      self.`revision` = try container.decode(String.self, forKey: .`revision`)
      self.`owner` = try container.decodeIfPresent(DashboardAPI.Owner.self, forKey: .`owner`)
      self.`createdAt` = try container.decode(String.self, forKey: .`createdAt`)
      self.`updatedAt` = try container.decode(String.self, forKey: .`updatedAt`)
      self.`startedAt` = try container.decodeIfPresent(String.self, forKey: .`startedAt`)
      self.`completedAt` = try container.decodeIfPresent(String.self, forKey: .`completedAt`)
      self.`desiredState` = try container.decode(String.self, forKey: .`desiredState`)
      self.`phase` = try container.decode(String.self, forKey: .`phase`)
      self.`outcome` = try container.decodeIfPresent(String.self, forKey: .`outcome`)
      self.`confidence` = try container.decode(String.self, forKey: .`confidence`)
      self.`labels` = try container.decode([String: String].self, forKey: .`labels`)
      self.`scheduler` = try container.decodeIfPresent(DashboardAPI.Scheduler.self, forKey: .`scheduler`)
      self.`disposition` = try container.decodeIfPresent(String.self, forKey: .`disposition`)
      self.`targetGenerationId` = try container.decodeIfPresent(String.self, forKey: .`targetGenerationId`)
      self.`imported` = try container.decodeIfPresent(Bool.self, forKey: .`imported`)
      self.`lifecycle` = try container.decodeIfPresent(DashboardAPI.Lifecycle.self, forKey: .`lifecycle`)
      self.`currentRun` = try container.decodeIfPresent(DashboardAPI.RunReference.self, forKey: .`currentRun`)
      self.`group` = try container.decodeIfPresent(DashboardAPI.GroupReference.self, forKey: .`group`)
    }
  }

  public struct JobDetail: Codable, Sendable {
    public var `job`: DashboardAPI.Job
    public var `fetchedAt`: String
    public init(job: DashboardAPI.Job, fetchedAt: String) {
      self.`job` = `job`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `job`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`job` = try container.decode(DashboardAPI.Job.self, forKey: .`job`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct JobPage: Codable, Sendable {
    public var `items`: [DashboardAPI.Job]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.Job], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.Job].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct JobRef: Codable, Sendable {
    public var `deploymentId`: String
    public var `namespaceId`: String
    public var `jobId`: String
    public init(deploymentId: String, namespaceId: String, jobId: String) {
      self.`deploymentId` = `deploymentId`
      self.`namespaceId` = `namespaceId`
      self.`jobId` = `jobId`
    }
    private enum CodingKeys: String, CodingKey {
      case `deploymentId`
      case `namespaceId`
      case `jobId`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`deploymentId` = try container.decode(String.self, forKey: .`deploymentId`)
      self.`namespaceId` = try container.decode(String.self, forKey: .`namespaceId`)
      self.`jobId` = try container.decode(String.self, forKey: .`jobId`)
    }
  }

  public struct Lifecycle: Codable, Sendable {
    public var `startedRecordedAt`: String?
    public var `startedProvenance`: String?
    public var `completedRecordedAt`: String?
    public var `completedProvenance`: String?
    public init(startedRecordedAt: String? = nil, startedProvenance: String? = nil, completedRecordedAt: String? = nil, completedProvenance: String? = nil) {
      self.`startedRecordedAt` = `startedRecordedAt`
      self.`startedProvenance` = `startedProvenance`
      self.`completedRecordedAt` = `completedRecordedAt`
      self.`completedProvenance` = `completedProvenance`
    }
    private enum CodingKeys: String, CodingKey {
      case `startedRecordedAt`
      case `startedProvenance`
      case `completedRecordedAt`
      case `completedProvenance`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`startedRecordedAt` = try container.decodeIfPresent(String.self, forKey: .`startedRecordedAt`)
      self.`startedProvenance` = try container.decodeIfPresent(String.self, forKey: .`startedProvenance`)
      self.`completedRecordedAt` = try container.decodeIfPresent(String.self, forKey: .`completedRecordedAt`)
      self.`completedProvenance` = try container.decodeIfPresent(String.self, forKey: .`completedProvenance`)
    }
  }

  public struct Limits: Codable, Sendable {
    public var `defaultPageSize`: Int64
    public var `maxPageSize`: Int64
    public var `logReadBytes`: Int64
    public var `logBufferBytes`: Int64
    public var `graphNodes`: Int64
    public var `graphEdges`: Int64
    public init(defaultPageSize: Int64, maxPageSize: Int64, logReadBytes: Int64, logBufferBytes: Int64, graphNodes: Int64, graphEdges: Int64) {
      self.`defaultPageSize` = `defaultPageSize`
      self.`maxPageSize` = `maxPageSize`
      self.`logReadBytes` = `logReadBytes`
      self.`logBufferBytes` = `logBufferBytes`
      self.`graphNodes` = `graphNodes`
      self.`graphEdges` = `graphEdges`
    }
    private enum CodingKeys: String, CodingKey {
      case `defaultPageSize`
      case `maxPageSize`
      case `logReadBytes`
      case `logBufferBytes`
      case `graphNodes`
      case `graphEdges`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`defaultPageSize` = try container.decode(Int64.self, forKey: .`defaultPageSize`)
      self.`maxPageSize` = try container.decode(Int64.self, forKey: .`maxPageSize`)
      self.`logReadBytes` = try container.decode(Int64.self, forKey: .`logReadBytes`)
      self.`logBufferBytes` = try container.decode(Int64.self, forKey: .`logBufferBytes`)
      self.`graphNodes` = try container.decode(Int64.self, forKey: .`graphNodes`)
      self.`graphEdges` = try container.decode(Int64.self, forKey: .`graphEdges`)
    }
  }

  public struct LogRange: Codable, Sendable {
    public var `bytesBase64`: String
    public var `executionId`: String
    public var `stream`: String
    public var `runId`: String?
    public var `startOffset`: String
    public var `endOffset`: String
    public var `nextCursor`: String?
    public var `state`: String
    public var `truncated`: Bool?
    public var `capturedAt`: String?
    public init(bytesBase64: String, executionId: String, stream: String, runId: String? = nil, startOffset: String, endOffset: String, nextCursor: String? = nil, state: String, truncated: Bool? = nil, capturedAt: String? = nil) {
      self.`bytesBase64` = `bytesBase64`
      self.`executionId` = `executionId`
      self.`stream` = `stream`
      self.`runId` = `runId`
      self.`startOffset` = `startOffset`
      self.`endOffset` = `endOffset`
      self.`nextCursor` = `nextCursor`
      self.`state` = `state`
      self.`truncated` = `truncated`
      self.`capturedAt` = `capturedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `bytesBase64`
      case `executionId`
      case `stream`
      case `runId`
      case `startOffset`
      case `endOffset`
      case `nextCursor`
      case `state`
      case `truncated`
      case `capturedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`bytesBase64` = try container.decode(String.self, forKey: .`bytesBase64`)
      self.`executionId` = try container.decode(String.self, forKey: .`executionId`)
      self.`stream` = try container.decode(String.self, forKey: .`stream`)
      self.`runId` = try container.decodeIfPresent(String.self, forKey: .`runId`)
      self.`startOffset` = try container.decode(String.self, forKey: .`startOffset`)
      self.`endOffset` = try container.decode(String.self, forKey: .`endOffset`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`state` = try container.decode(String.self, forKey: .`state`)
      self.`truncated` = try container.decodeIfPresent(Bool.self, forKey: .`truncated`)
      self.`capturedAt` = try container.decodeIfPresent(String.self, forKey: .`capturedAt`)
    }
  }

  public struct Namespace: Codable, Sendable {
    public var `id`: String
    public var `name`: String
    public var `roles`: [String]
    public var `capabilities`: [String]
    public var `authorizationVersion`: String
    public var `authorizationCheckedAt`: String
    public var `authorizationExpiresAt`: String
    public init(id: String, name: String, roles: [String], capabilities: [String], authorizationVersion: String, authorizationCheckedAt: String, authorizationExpiresAt: String) {
      self.`id` = `id`
      self.`name` = `name`
      self.`roles` = `roles`
      self.`capabilities` = `capabilities`
      self.`authorizationVersion` = `authorizationVersion`
      self.`authorizationCheckedAt` = `authorizationCheckedAt`
      self.`authorizationExpiresAt` = `authorizationExpiresAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `name`
      case `roles`
      case `capabilities`
      case `authorizationVersion`
      case `authorizationCheckedAt`
      case `authorizationExpiresAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`name` = try container.decode(String.self, forKey: .`name`)
      self.`roles` = try container.decode([String].self, forKey: .`roles`)
      self.`capabilities` = try container.decode([String].self, forKey: .`capabilities`)
      self.`authorizationVersion` = try container.decode(String.self, forKey: .`authorizationVersion`)
      self.`authorizationCheckedAt` = try container.decode(String.self, forKey: .`authorizationCheckedAt`)
      self.`authorizationExpiresAt` = try container.decode(String.self, forKey: .`authorizationExpiresAt`)
    }
  }

  public struct Overview: Codable, Sendable {
    public var `active`: Int64?
    public var `awaitingExecution`: Int64?
    public var `running`: Int64?
    public var `evidenceAttention`: Int64?
    public var `missingCompletionTime`: Int64?
    public var `terminal`: [String: Int64?]
    public var `window`: DashboardAPI.Window
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(active: Int64?, awaitingExecution: Int64?, running: Int64?, evidenceAttention: Int64?, missingCompletionTime: Int64?, terminal: [String: Int64?], window: DashboardAPI.Window, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`active` = `active`
      self.`awaitingExecution` = `awaitingExecution`
      self.`running` = `running`
      self.`evidenceAttention` = `evidenceAttention`
      self.`missingCompletionTime` = `missingCompletionTime`
      self.`terminal` = `terminal`
      self.`window` = `window`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `active`
      case `awaitingExecution`
      case `running`
      case `evidenceAttention`
      case `missingCompletionTime`
      case `terminal`
      case `window`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`active` = try container.decode(Int64?.self, forKey: .`active`)
      self.`awaitingExecution` = try container.decode(Int64?.self, forKey: .`awaitingExecution`)
      self.`running` = try container.decode(Int64?.self, forKey: .`running`)
      self.`evidenceAttention` = try container.decode(Int64?.self, forKey: .`evidenceAttention`)
      self.`missingCompletionTime` = try container.decode(Int64?.self, forKey: .`missingCompletionTime`)
      self.`terminal` = try container.decode([String: Int64?].self, forKey: .`terminal`)
      self.`window` = try container.decode(DashboardAPI.Window.self, forKey: .`window`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct Owner: Codable, Sendable {
    public var `id`: String
    public var `displayName`: String?
    public var `isCurrentUser`: Bool
    public init(id: String, displayName: String? = nil, isCurrentUser: Bool) {
      self.`id` = `id`
      self.`displayName` = `displayName`
      self.`isCurrentUser` = `isCurrentUser`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `displayName`
      case `isCurrentUser`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`displayName` = try container.decodeIfPresent(String.self, forKey: .`displayName`)
      self.`isCurrentUser` = try container.decode(Bool.self, forKey: .`isCurrentUser`)
    }
  }

  public struct Preferences: Codable, Sendable {
    public var `revision`: String
    public var `timezone`: String
    public var `appearance`: String
    public var `refreshSeconds`: Int64
    public init(revision: String, timezone: String, appearance: String, refreshSeconds: Int64) {
      self.`revision` = `revision`
      self.`timezone` = `timezone`
      self.`appearance` = `appearance`
      self.`refreshSeconds` = `refreshSeconds`
    }
    private enum CodingKeys: String, CodingKey {
      case `revision`
      case `timezone`
      case `appearance`
      case `refreshSeconds`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`revision` = try container.decode(String.self, forKey: .`revision`)
      self.`timezone` = try container.decode(String.self, forKey: .`timezone`)
      self.`appearance` = try container.decode(String.self, forKey: .`appearance`)
      self.`refreshSeconds` = try container.decode(Int64.self, forKey: .`refreshSeconds`)
    }
  }

  public struct ReadUpdate: Codable, Sendable {
    public var `read`: Bool
    public init(read: Bool) {
      self.`read` = `read`
    }
    private enum CodingKeys: String, CodingKey {
      case `read`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`read` = try container.decode(Bool.self, forKey: .`read`)
    }
  }

  public struct Report: Codable, Sendable {
    public var `id`: String
    public var `state`: String
    public var `createdAt`: String?
    public var `sourceRevision`: String?
    public var `evidenceId`: String?
    public var `analysisEvidenceId`: String?
    public var `engineVersion`: String?
    public var `disclosure`: String?
    public var `findings`: [DashboardAPI.Finding]
    public var `missingEvidence`: [String]
    public var `warnings`: [String]?
    public var `retryAdvice`: String?
    public var `message`: String?
    public init(id: String, state: String, createdAt: String? = nil, sourceRevision: String? = nil, evidenceId: String? = nil, analysisEvidenceId: String? = nil, engineVersion: String? = nil, disclosure: String? = nil, findings: [DashboardAPI.Finding], missingEvidence: [String], warnings: [String]? = nil, retryAdvice: String? = nil, message: String? = nil) {
      self.`id` = `id`
      self.`state` = `state`
      self.`createdAt` = `createdAt`
      self.`sourceRevision` = `sourceRevision`
      self.`evidenceId` = `evidenceId`
      self.`analysisEvidenceId` = `analysisEvidenceId`
      self.`engineVersion` = `engineVersion`
      self.`disclosure` = `disclosure`
      self.`findings` = `findings`
      self.`missingEvidence` = `missingEvidence`
      self.`warnings` = `warnings`
      self.`retryAdvice` = `retryAdvice`
      self.`message` = `message`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `state`
      case `createdAt`
      case `sourceRevision`
      case `evidenceId`
      case `analysisEvidenceId`
      case `engineVersion`
      case `disclosure`
      case `findings`
      case `missingEvidence`
      case `warnings`
      case `retryAdvice`
      case `message`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`state` = try container.decode(String.self, forKey: .`state`)
      self.`createdAt` = try container.decodeIfPresent(String.self, forKey: .`createdAt`)
      self.`sourceRevision` = try container.decodeIfPresent(String.self, forKey: .`sourceRevision`)
      self.`evidenceId` = try container.decodeIfPresent(String.self, forKey: .`evidenceId`)
      self.`analysisEvidenceId` = try container.decodeIfPresent(String.self, forKey: .`analysisEvidenceId`)
      self.`engineVersion` = try container.decodeIfPresent(String.self, forKey: .`engineVersion`)
      self.`disclosure` = try container.decodeIfPresent(String.self, forKey: .`disclosure`)
      self.`findings` = try container.decode([DashboardAPI.Finding].self, forKey: .`findings`)
      self.`missingEvidence` = try container.decode([String].self, forKey: .`missingEvidence`)
      self.`warnings` = try container.decodeIfPresent([String].self, forKey: .`warnings`)
      self.`retryAdvice` = try container.decodeIfPresent(String.self, forKey: .`retryAdvice`)
      self.`message` = try container.decodeIfPresent(String.self, forKey: .`message`)
    }
  }

  public struct ReportPage: Codable, Sendable {
    public var `items`: [DashboardAPI.Report]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.Report], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.Report].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct ReportRequest: Codable, Sendable {
    public var `includeLogTail`: Bool
    public var `runId`: String?
    public init(includeLogTail: Bool, runId: String? = nil) {
      self.`includeLogTail` = `includeLogTail`
      self.`runId` = `runId`
    }
    private enum CodingKeys: String, CodingKey {
      case `includeLogTail`
      case `runId`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`includeLogTail` = try container.decode(Bool.self, forKey: .`includeLogTail`)
      self.`runId` = try container.decodeIfPresent(String.self, forKey: .`runId`)
    }
  }

  public struct Rule: Codable, Sendable {
    public var `id`: String
    public var `revision`: String
    public var `name`: String
    public var `enabled`: Bool
    public var `scope`: String
    public var `namespaces`: [DashboardAPI.Scope]
    public var `jobs`: [DashboardAPI.JobRef]
    public var `outcomeMode`: String
    public var `outcomes`: [String]
    public var `activation`: [DashboardAPI.RuleActivation]?
    public init(id: String, revision: String, name: String, enabled: Bool, scope: String, namespaces: [DashboardAPI.Scope], jobs: [DashboardAPI.JobRef], outcomeMode: String, outcomes: [String], activation: [DashboardAPI.RuleActivation]? = nil) {
      self.`id` = `id`
      self.`revision` = `revision`
      self.`name` = `name`
      self.`enabled` = `enabled`
      self.`scope` = `scope`
      self.`namespaces` = `namespaces`
      self.`jobs` = `jobs`
      self.`outcomeMode` = `outcomeMode`
      self.`outcomes` = `outcomes`
      self.`activation` = `activation`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `revision`
      case `name`
      case `enabled`
      case `scope`
      case `namespaces`
      case `jobs`
      case `outcomeMode`
      case `outcomes`
      case `activation`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`revision` = try container.decode(String.self, forKey: .`revision`)
      self.`name` = try container.decode(String.self, forKey: .`name`)
      self.`enabled` = try container.decode(Bool.self, forKey: .`enabled`)
      self.`scope` = try container.decode(String.self, forKey: .`scope`)
      self.`namespaces` = try container.decode([DashboardAPI.Scope].self, forKey: .`namespaces`)
      self.`jobs` = try container.decode([DashboardAPI.JobRef].self, forKey: .`jobs`)
      self.`outcomeMode` = try container.decode(String.self, forKey: .`outcomeMode`)
      self.`outcomes` = try container.decode([String].self, forKey: .`outcomes`)
      self.`activation` = try container.decodeIfPresent([DashboardAPI.RuleActivation].self, forKey: .`activation`)
    }
  }

  public struct RuleActivation: Codable, Sendable {
    public var `deploymentId`: String
    public var `status`: String
    public init(deploymentId: String, status: String) {
      self.`deploymentId` = `deploymentId`
      self.`status` = `status`
    }
    private enum CodingKeys: String, CodingKey {
      case `deploymentId`
      case `status`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`deploymentId` = try container.decode(String.self, forKey: .`deploymentId`)
      self.`status` = try container.decode(String.self, forKey: .`status`)
    }
  }

  public struct RuleInput: Codable, Sendable {
    public var `name`: String
    public var `enabled`: Bool
    public var `scope`: String
    public var `namespaces`: [DashboardAPI.Scope]
    public var `jobs`: [DashboardAPI.JobRef]
    public var `outcomeMode`: String
    public var `outcomes`: [String]
    public init(name: String, enabled: Bool, scope: String, namespaces: [DashboardAPI.Scope], jobs: [DashboardAPI.JobRef], outcomeMode: String, outcomes: [String]) {
      self.`name` = `name`
      self.`enabled` = `enabled`
      self.`scope` = `scope`
      self.`namespaces` = `namespaces`
      self.`jobs` = `jobs`
      self.`outcomeMode` = `outcomeMode`
      self.`outcomes` = `outcomes`
    }
    private enum CodingKeys: String, CodingKey {
      case `name`
      case `enabled`
      case `scope`
      case `namespaces`
      case `jobs`
      case `outcomeMode`
      case `outcomes`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`name` = try container.decode(String.self, forKey: .`name`)
      self.`enabled` = try container.decode(Bool.self, forKey: .`enabled`)
      self.`scope` = try container.decode(String.self, forKey: .`scope`)
      self.`namespaces` = try container.decode([DashboardAPI.Scope].self, forKey: .`namespaces`)
      self.`jobs` = try container.decode([DashboardAPI.JobRef].self, forKey: .`jobs`)
      self.`outcomeMode` = try container.decode(String.self, forKey: .`outcomeMode`)
      self.`outcomes` = try container.decode([String].self, forKey: .`outcomes`)
    }
  }

  public struct RulePage: Codable, Sendable {
    public var `items`: [DashboardAPI.Rule]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.Rule], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.Rule].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct RunReference: Codable, Sendable {
    public var `id`: String
    public var `number`: String
    public var `executionId`: String?
    public init(id: String, number: String, executionId: String? = nil) {
      self.`id` = `id`
      self.`number` = `number`
      self.`executionId` = `executionId`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `number`
      case `executionId`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`number` = try container.decode(String.self, forKey: .`number`)
      self.`executionId` = try container.decodeIfPresent(String.self, forKey: .`executionId`)
    }
  }

  public struct Scheduler: Codable, Sendable {
    public var `state`: String?
    public var `jobId`: String?
    public var `observedAt`: String?
    public var `reason`: String?
    public var `cluster`: String?
    public init(state: String? = nil, jobId: String? = nil, observedAt: String? = nil, reason: String? = nil, cluster: String? = nil) {
      self.`state` = `state`
      self.`jobId` = `jobId`
      self.`observedAt` = `observedAt`
      self.`reason` = `reason`
      self.`cluster` = `cluster`
    }
    private enum CodingKeys: String, CodingKey {
      case `state`
      case `jobId`
      case `observedAt`
      case `reason`
      case `cluster`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`state` = try container.decodeIfPresent(String.self, forKey: .`state`)
      self.`jobId` = try container.decodeIfPresent(String.self, forKey: .`jobId`)
      self.`observedAt` = try container.decodeIfPresent(String.self, forKey: .`observedAt`)
      self.`reason` = try container.decodeIfPresent(String.self, forKey: .`reason`)
      self.`cluster` = try container.decodeIfPresent(String.self, forKey: .`cluster`)
    }
  }

  public struct Scope: Codable, Sendable {
    public var `deploymentId`: String
    public var `namespaceId`: String
    public init(deploymentId: String, namespaceId: String) {
      self.`deploymentId` = `deploymentId`
      self.`namespaceId` = `namespaceId`
    }
    private enum CodingKeys: String, CodingKey {
      case `deploymentId`
      case `namespaceId`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`deploymentId` = try container.decode(String.self, forKey: .`deploymentId`)
      self.`namespaceId` = try container.decode(String.self, forKey: .`namespaceId`)
    }
  }

  public struct SourceStatus: Codable, Sendable {
    public var `deploymentId`: String
    public var `namespaceId`: String
    public var `status`: String
    public var `asOf`: String?
    public var `fetchedAt`: String
    public var `message`: String?
    public init(deploymentId: String, namespaceId: String, status: String, asOf: String? = nil, fetchedAt: String, message: String? = nil) {
      self.`deploymentId` = `deploymentId`
      self.`namespaceId` = `namespaceId`
      self.`status` = `status`
      self.`asOf` = `asOf`
      self.`fetchedAt` = `fetchedAt`
      self.`message` = `message`
    }
    private enum CodingKeys: String, CodingKey {
      case `deploymentId`
      case `namespaceId`
      case `status`
      case `asOf`
      case `fetchedAt`
      case `message`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`deploymentId` = try container.decode(String.self, forKey: .`deploymentId`)
      self.`namespaceId` = try container.decode(String.self, forKey: .`namespaceId`)
      self.`status` = try container.decode(String.self, forKey: .`status`)
      self.`asOf` = try container.decodeIfPresent(String.self, forKey: .`asOf`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
      self.`message` = try container.decodeIfPresent(String.self, forKey: .`message`)
    }
  }

  public struct Target: Codable, Sendable {
    public var `deploymentId`: String
    public var `namespaceId`: String
    public var `targetId`: String
    public var `name`: String
    public var `state`: String
    public var `provider`: String?
    public var `backend`: String?
    public var `generation`: String?
    public var `capabilities`: [String]
    public init(deploymentId: String, namespaceId: String, targetId: String, name: String, state: String, provider: String? = nil, backend: String? = nil, generation: String? = nil, capabilities: [String]) {
      self.`deploymentId` = `deploymentId`
      self.`namespaceId` = `namespaceId`
      self.`targetId` = `targetId`
      self.`name` = `name`
      self.`state` = `state`
      self.`provider` = `provider`
      self.`backend` = `backend`
      self.`generation` = `generation`
      self.`capabilities` = `capabilities`
    }
    private enum CodingKeys: String, CodingKey {
      case `deploymentId`
      case `namespaceId`
      case `targetId`
      case `name`
      case `state`
      case `provider`
      case `backend`
      case `generation`
      case `capabilities`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`deploymentId` = try container.decode(String.self, forKey: .`deploymentId`)
      self.`namespaceId` = try container.decode(String.self, forKey: .`namespaceId`)
      self.`targetId` = try container.decode(String.self, forKey: .`targetId`)
      self.`name` = try container.decode(String.self, forKey: .`name`)
      self.`state` = try container.decode(String.self, forKey: .`state`)
      self.`provider` = try container.decodeIfPresent(String.self, forKey: .`provider`)
      self.`backend` = try container.decodeIfPresent(String.self, forKey: .`backend`)
      self.`generation` = try container.decodeIfPresent(String.self, forKey: .`generation`)
      self.`capabilities` = try container.decode([String].self, forKey: .`capabilities`)
    }
  }

  public struct TargetPage: Codable, Sendable {
    public var `items`: [DashboardAPI.Target]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.Target], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.Target].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

  public struct Window: Codable, Sendable {
    public var `from`: String
    public var `to`: String
    public init(from: String, to: String) {
      self.`from` = `from`
      self.`to` = `to`
    }
    private enum CodingKeys: String, CodingKey {
      case `from`
      case `to`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`from` = try container.decode(String.self, forKey: .`from`)
      self.`to` = try container.decode(String.self, forKey: .`to`)
    }
  }

  public struct Workload: Codable, Sendable {
    public var `deploymentId`: String
    public var `namespaceId`: String
    public var `id`: String
    public var `name`: String?
    public var `kind`: String
    public var `createdAt`: String
    public var `totalChildren`: String
    public var `counts`: [String: String]
    public var `concurrency`: String?
    public var `failurePolicy`: String?
    public var `arrayId`: String?
    public init(deploymentId: String, namespaceId: String, id: String, name: String? = nil, kind: String, createdAt: String, totalChildren: String, counts: [String: String], concurrency: String? = nil, failurePolicy: String? = nil, arrayId: String? = nil) {
      self.`deploymentId` = `deploymentId`
      self.`namespaceId` = `namespaceId`
      self.`id` = `id`
      self.`name` = `name`
      self.`kind` = `kind`
      self.`createdAt` = `createdAt`
      self.`totalChildren` = `totalChildren`
      self.`counts` = `counts`
      self.`concurrency` = `concurrency`
      self.`failurePolicy` = `failurePolicy`
      self.`arrayId` = `arrayId`
    }
    private enum CodingKeys: String, CodingKey {
      case `deploymentId`
      case `namespaceId`
      case `id`
      case `name`
      case `kind`
      case `createdAt`
      case `totalChildren`
      case `counts`
      case `concurrency`
      case `failurePolicy`
      case `arrayId`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`deploymentId` = try container.decode(String.self, forKey: .`deploymentId`)
      self.`namespaceId` = try container.decode(String.self, forKey: .`namespaceId`)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`name` = try container.decodeIfPresent(String.self, forKey: .`name`)
      self.`kind` = try container.decode(String.self, forKey: .`kind`)
      self.`createdAt` = try container.decode(String.self, forKey: .`createdAt`)
      self.`totalChildren` = try container.decode(String.self, forKey: .`totalChildren`)
      self.`counts` = try container.decode([String: String].self, forKey: .`counts`)
      self.`concurrency` = try container.decodeIfPresent(String.self, forKey: .`concurrency`)
      self.`failurePolicy` = try container.decodeIfPresent(String.self, forKey: .`failurePolicy`)
      self.`arrayId` = try container.decodeIfPresent(String.self, forKey: .`arrayId`)
    }
  }

  public struct WorkloadChild: Codable, Sendable {
    public var `id`: String
    public var `job`: DashboardAPI.Job
    public var `readiness`: String?
    public var `disposition`: String?
    public var `taskIndex`: String?
    public var `dependencies`: [DashboardAPI.Dependency]?
    public init(id: String, job: DashboardAPI.Job, readiness: String? = nil, disposition: String? = nil, taskIndex: String? = nil, dependencies: [DashboardAPI.Dependency]? = nil) {
      self.`id` = `id`
      self.`job` = `job`
      self.`readiness` = `readiness`
      self.`disposition` = `disposition`
      self.`taskIndex` = `taskIndex`
      self.`dependencies` = `dependencies`
    }
    private enum CodingKeys: String, CodingKey {
      case `id`
      case `job`
      case `readiness`
      case `disposition`
      case `taskIndex`
      case `dependencies`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`id` = try container.decode(String.self, forKey: .`id`)
      self.`job` = try container.decode(DashboardAPI.Job.self, forKey: .`job`)
      self.`readiness` = try container.decodeIfPresent(String.self, forKey: .`readiness`)
      self.`disposition` = try container.decodeIfPresent(String.self, forKey: .`disposition`)
      self.`taskIndex` = try container.decodeIfPresent(String.self, forKey: .`taskIndex`)
      self.`dependencies` = try container.decodeIfPresent([DashboardAPI.Dependency].self, forKey: .`dependencies`)
    }
  }

  public struct WorkloadDetail: Codable, Sendable {
    public var `workload`: DashboardAPI.Workload
    public var `children`: [DashboardAPI.WorkloadChild]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public var `omittedNodes`: String?
    public var `omittedEdges`: String?
    public init(workload: DashboardAPI.Workload, children: [DashboardAPI.WorkloadChild], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String, omittedNodes: String? = nil, omittedEdges: String? = nil) {
      self.`workload` = `workload`
      self.`children` = `children`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
      self.`omittedNodes` = `omittedNodes`
      self.`omittedEdges` = `omittedEdges`
    }
    private enum CodingKeys: String, CodingKey {
      case `workload`
      case `children`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
      case `omittedNodes`
      case `omittedEdges`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`workload` = try container.decode(DashboardAPI.Workload.self, forKey: .`workload`)
      self.`children` = try container.decode([DashboardAPI.WorkloadChild].self, forKey: .`children`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
      self.`omittedNodes` = try container.decodeIfPresent(String.self, forKey: .`omittedNodes`)
      self.`omittedEdges` = try container.decodeIfPresent(String.self, forKey: .`omittedEdges`)
    }
  }

  public struct WorkloadPage: Codable, Sendable {
    public var `items`: [DashboardAPI.Workload]
    public var `nextCursor`: String?
    public var `completeness`: String
    public var `sources`: [DashboardAPI.SourceStatus]
    public var `fetchedAt`: String
    public init(items: [DashboardAPI.Workload], nextCursor: String? = nil, completeness: String, sources: [DashboardAPI.SourceStatus], fetchedAt: String) {
      self.`items` = `items`
      self.`nextCursor` = `nextCursor`
      self.`completeness` = `completeness`
      self.`sources` = `sources`
      self.`fetchedAt` = `fetchedAt`
    }
    private enum CodingKeys: String, CodingKey {
      case `items`
      case `nextCursor`
      case `completeness`
      case `sources`
      case `fetchedAt`
    }
    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.`items` = try container.decode([DashboardAPI.Workload].self, forKey: .`items`)
      self.`nextCursor` = try container.decodeIfPresent(String.self, forKey: .`nextCursor`)
      self.`completeness` = try container.decode(String.self, forKey: .`completeness`)
      self.`sources` = try container.decode([DashboardAPI.SourceStatus].self, forKey: .`sources`)
      self.`fetchedAt` = try container.decode(String.self, forKey: .`fetchedAt`)
    }
  }

}

public struct ArtifactsQuery: Sendable {
  public var `cursor`: String?
  public var `limit`: Int64?
  public init(cursor: String? = nil, limit: Int64? = nil) {
    self.`cursor` = `cursor`
    self.`limit` = `limit`
  }
}

public struct LogsQuery: Sendable {
  public var `cursor`: String?
  public var `stream`: String?
  public var `limitBytes`: Int64?
  public init(cursor: String? = nil, stream: String? = nil, limitBytes: Int64? = nil) {
    self.`cursor` = `cursor`
    self.`stream` = `stream`
    self.`limitBytes` = `limitBytes`
  }
}

public struct ReportsQuery: Sendable {
  public var `cursor`: String?
  public var `limit`: Int64?
  public init(cursor: String? = nil, limit: Int64? = nil) {
    self.`cursor` = `cursor`
    self.`limit` = `limit`
  }
}

public struct RequestReportHeaders: Sendable {
  public var `xCSRFToken`: String?
  public var `idempotencyKey`: String
  public init(xCSRFToken: String? = nil, idempotencyKey: String) {
    self.`xCSRFToken` = `xCSRFToken`
    self.`idempotencyKey` = `idempotencyKey`
  }
}

public struct WorkloadQuery: Sendable {
  public var `cursor`: String?
  public var `limit`: Int64?
  public init(cursor: String? = nil, limit: Int64? = nil) {
    self.`cursor` = `cursor`
    self.`limit` = `limit`
  }
}

public struct DevicesQuery: Sendable {
  public var `cursor`: String?
  public var `limit`: Int64?
  public init(cursor: String? = nil, limit: Int64? = nil) {
    self.`cursor` = `cursor`
    self.`limit` = `limit`
  }
}

public struct UpdateDeviceHeaders: Sendable {
  public var `xCSRFToken`: String?
  public init(xCSRFToken: String? = nil) {
    self.`xCSRFToken` = `xCSRFToken`
  }
}

public struct InboxQuery: Sendable {
  public var `cursor`: String?
  public var `limit`: Int64?
  public var `unread`: Bool?
  public init(cursor: String? = nil, limit: Int64? = nil, unread: Bool? = nil) {
    self.`cursor` = `cursor`
    self.`limit` = `limit`
    self.`unread` = `unread`
  }
}

public struct UpdateInboxHeaders: Sendable {
  public var `xCSRFToken`: String?
  public init(xCSRFToken: String? = nil) {
    self.`xCSRFToken` = `xCSRFToken`
  }
}

public struct JobsQuery: Sendable {
  public var `scope`: String?
  public var `cursor`: String?
  public var `phase`: String?
  public var `outcome`: String?
  public var `owner`: String?
  public var `jobId`: String?
  public var `from`: String?
  public var `to`: String?
  public var `completedFrom`: String?
  public var `completedTo`: String?
  public var `attention`: Bool?
  public var `limit`: Int64?
  public init(scope: String? = nil, cursor: String? = nil, phase: String? = nil, outcome: String? = nil, owner: String? = nil, jobId: String? = nil, from: String? = nil, to: String? = nil, completedFrom: String? = nil, completedTo: String? = nil, attention: Bool? = nil, limit: Int64? = nil) {
    self.`scope` = `scope`
    self.`cursor` = `cursor`
    self.`phase` = `phase`
    self.`outcome` = `outcome`
    self.`owner` = `owner`
    self.`jobId` = `jobId`
    self.`from` = `from`
    self.`to` = `to`
    self.`completedFrom` = `completedFrom`
    self.`completedTo` = `completedTo`
    self.`attention` = `attention`
    self.`limit` = `limit`
  }
}

public struct OverviewQuery: Sendable {
  public var `scope`: String?
  public var `from`: String?
  public var `to`: String?
  public var `completedFrom`: String?
  public var `completedTo`: String?
  public var `windowHours`: Int64?
  public init(scope: String? = nil, from: String? = nil, to: String? = nil, completedFrom: String? = nil, completedTo: String? = nil, windowHours: Int64? = nil) {
    self.`scope` = `scope`
    self.`from` = `from`
    self.`to` = `to`
    self.`completedFrom` = `completedFrom`
    self.`completedTo` = `completedTo`
    self.`windowHours` = `windowHours`
  }
}

public struct UpdatePreferencesHeaders: Sendable {
  public var `xCSRFToken`: String?
  public var `ifMatch`: String
  public init(xCSRFToken: String? = nil, ifMatch: String) {
    self.`xCSRFToken` = `xCSRFToken`
    self.`ifMatch` = `ifMatch`
  }
}

public struct RulesQuery: Sendable {
  public var `cursor`: String?
  public var `limit`: Int64?
  public init(cursor: String? = nil, limit: Int64? = nil) {
    self.`cursor` = `cursor`
    self.`limit` = `limit`
  }
}

public struct CreateRuleHeaders: Sendable {
  public var `xCSRFToken`: String?
  public var `idempotencyKey`: String
  public init(xCSRFToken: String? = nil, idempotencyKey: String) {
    self.`xCSRFToken` = `xCSRFToken`
    self.`idempotencyKey` = `idempotencyKey`
  }
}

public struct UpdateRuleHeaders: Sendable {
  public var `xCSRFToken`: String?
  public var `ifMatch`: String
  public init(xCSRFToken: String? = nil, ifMatch: String) {
    self.`xCSRFToken` = `xCSRFToken`
    self.`ifMatch` = `ifMatch`
  }
}

public struct TargetsQuery: Sendable {
  public var `scope`: String?
  public var `cursor`: String?
  public var `limit`: Int64?
  public init(scope: String? = nil, cursor: String? = nil, limit: Int64? = nil) {
    self.`scope` = `scope`
    self.`cursor` = `cursor`
    self.`limit` = `limit`
  }
}

public struct WorkloadsQuery: Sendable {
  public var `scope`: String?
  public var `cursor`: String?
  public var `limit`: Int64?
  public init(scope: String? = nil, cursor: String? = nil, limit: Int64? = nil) {
    self.`scope` = `scope`
    self.`cursor` = `cursor`
    self.`limit` = `limit`
  }
}

public struct DashboardHTTPRequest: Sendable {
  public let method: String
  public let path: String
  public let query: [String: String]
  public let headers: [String: String]
  public let body: Data?
}

/// Transport must enforce the approved origin, authentication, no-store, cancellation, response bounds and non-2xx errors.
public protocol DashboardHTTPTransport: Sendable {
  func send(_ request: DashboardHTTPRequest) async throws -> Data
}

public struct DashboardClient: Sendable {
  private let transport: any DashboardHTTPTransport
  public init(transport: any DashboardHTTPTransport) { self.transport = transport }
  private func segment(_ value: String) -> String {
    value.addingPercentEncoding(withAllowedCharacters: CharacterSet(charactersIn: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~"))!
  }
  public func bootstrap() async throws -> DashboardAPI.Bootstrap {
    let queryValues: [String: String] = [:]
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/bootstrap", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Bootstrap.self, from: data)
  }
  public func job(deploymentId: String, namespaceId: String, jobId: String) async throws -> DashboardAPI.JobDetail {
    let queryValues: [String: String] = [:]
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/deployments/\(segment(deploymentId))/namespaces/\(segment(namespaceId))/jobs/\(segment(jobId))", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.JobDetail.self, from: data)
  }
  public func artifacts(deploymentId: String, namespaceId: String, jobId: String, query: ArtifactsQuery = .init()) async throws -> DashboardAPI.ArtifactPage {
    var queryValues: [String: String] = [:]
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/deployments/\(segment(deploymentId))/namespaces/\(segment(namespaceId))/jobs/\(segment(jobId))/artifacts", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.ArtifactPage.self, from: data)
  }
  public func logs(deploymentId: String, namespaceId: String, jobId: String, query: LogsQuery = .init()) async throws -> DashboardAPI.LogRange {
    var queryValues: [String: String] = [:]
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`stream` { queryValues["stream"] = String(describing: value) }
    if let value = query.`limitBytes` { queryValues["limitBytes"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/deployments/\(segment(deploymentId))/namespaces/\(segment(namespaceId))/jobs/\(segment(jobId))/logs", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.LogRange.self, from: data)
  }
  public func reports(deploymentId: String, namespaceId: String, jobId: String, query: ReportsQuery = .init()) async throws -> DashboardAPI.ReportPage {
    var queryValues: [String: String] = [:]
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/deployments/\(segment(deploymentId))/namespaces/\(segment(namespaceId))/jobs/\(segment(jobId))/reports", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.ReportPage.self, from: data)
  }
  public func requestReport(deploymentId: String, namespaceId: String, jobId: String, headers: RequestReportHeaders, body: DashboardAPI.ReportRequest) async throws -> DashboardAPI.Report {
    let queryValues: [String: String] = [:]
    var headersValues: [String: String] = [:]
    if let value = headers.`xCSRFToken` { headersValues["X-CSRF-Token"] = String(describing: value) }
    headersValues["Idempotency-Key"] = String(describing: headers.`idempotencyKey`)
    let request = DashboardHTTPRequest(method: "POST", path: "/api/v1/deployments/\(segment(deploymentId))/namespaces/\(segment(namespaceId))/jobs/\(segment(jobId))/reports", query: queryValues, headers: headersValues, body: try JSONEncoder().encode(body))
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Report.self, from: data)
  }
  public func citation(deploymentId: String, namespaceId: String, jobId: String, reportId: String, citationId: String) async throws -> DashboardAPI.Citation {
    let queryValues: [String: String] = [:]
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/deployments/\(segment(deploymentId))/namespaces/\(segment(namespaceId))/jobs/\(segment(jobId))/reports/\(segment(reportId))/citations/\(segment(citationId))", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Citation.self, from: data)
  }
  public func workload(deploymentId: String, namespaceId: String, kind: String, workloadId: String, query: WorkloadQuery = .init()) async throws -> DashboardAPI.WorkloadDetail {
    var queryValues: [String: String] = [:]
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/deployments/\(segment(deploymentId))/namespaces/\(segment(namespaceId))/workloads/\(segment(kind))/\(segment(workloadId))", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.WorkloadDetail.self, from: data)
  }
  public func devices(query: DevicesQuery = .init()) async throws -> DashboardAPI.DevicePage {
    var queryValues: [String: String] = [:]
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/devices", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.DevicePage.self, from: data)
  }
  public func updateDevice(deviceId: String, headers: UpdateDeviceHeaders = .init(), body: DashboardAPI.DeviceUpdate) async throws -> DashboardAPI.Device {
    let queryValues: [String: String] = [:]
    var headersValues: [String: String] = [:]
    if let value = headers.`xCSRFToken` { headersValues["X-CSRF-Token"] = String(describing: value) }
    let request = DashboardHTTPRequest(method: "PATCH", path: "/api/v1/devices/\(segment(deviceId))", query: queryValues, headers: headersValues, body: try JSONEncoder().encode(body))
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Device.self, from: data)
  }
  public func inbox(query: InboxQuery = .init()) async throws -> DashboardAPI.InboxItemPage {
    var queryValues: [String: String] = [:]
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    if let value = query.`unread` { queryValues["unread"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/inbox", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.InboxItemPage.self, from: data)
  }
  public func updateInbox(inboxId: String, headers: UpdateInboxHeaders = .init(), body: DashboardAPI.ReadUpdate) async throws -> DashboardAPI.InboxItem {
    let queryValues: [String: String] = [:]
    var headersValues: [String: String] = [:]
    if let value = headers.`xCSRFToken` { headersValues["X-CSRF-Token"] = String(describing: value) }
    let request = DashboardHTTPRequest(method: "PATCH", path: "/api/v1/inbox/\(segment(inboxId))", query: queryValues, headers: headersValues, body: try JSONEncoder().encode(body))
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.InboxItem.self, from: data)
  }
  public func jobs(query: JobsQuery = .init()) async throws -> DashboardAPI.JobPage {
    var queryValues: [String: String] = [:]
    if let value = query.`scope` { queryValues["scope"] = String(describing: value) }
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`phase` { queryValues["phase"] = String(describing: value) }
    if let value = query.`outcome` { queryValues["outcome"] = String(describing: value) }
    if let value = query.`owner` { queryValues["owner"] = String(describing: value) }
    if let value = query.`jobId` { queryValues["jobId"] = String(describing: value) }
    if let value = query.`from` { queryValues["from"] = String(describing: value) }
    if let value = query.`to` { queryValues["to"] = String(describing: value) }
    if let value = query.`completedFrom` { queryValues["completedFrom"] = String(describing: value) }
    if let value = query.`completedTo` { queryValues["completedTo"] = String(describing: value) }
    if let value = query.`attention` { queryValues["attention"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/jobs", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.JobPage.self, from: data)
  }
  public func overview(query: OverviewQuery = .init()) async throws -> DashboardAPI.Overview {
    var queryValues: [String: String] = [:]
    if let value = query.`scope` { queryValues["scope"] = String(describing: value) }
    if let value = query.`from` { queryValues["from"] = String(describing: value) }
    if let value = query.`to` { queryValues["to"] = String(describing: value) }
    if let value = query.`completedFrom` { queryValues["completedFrom"] = String(describing: value) }
    if let value = query.`completedTo` { queryValues["completedTo"] = String(describing: value) }
    if let value = query.`windowHours` { queryValues["windowHours"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/overview", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Overview.self, from: data)
  }
  public func updatePreferences(headers: UpdatePreferencesHeaders, body: DashboardAPI.Preferences) async throws -> DashboardAPI.Preferences {
    let queryValues: [String: String] = [:]
    var headersValues: [String: String] = [:]
    if let value = headers.`xCSRFToken` { headersValues["X-CSRF-Token"] = String(describing: value) }
    headersValues["If-Match"] = String(describing: headers.`ifMatch`)
    let request = DashboardHTTPRequest(method: "PUT", path: "/api/v1/preferences", query: queryValues, headers: headersValues, body: try JSONEncoder().encode(body))
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Preferences.self, from: data)
  }
  public func rules(query: RulesQuery = .init()) async throws -> DashboardAPI.RulePage {
    var queryValues: [String: String] = [:]
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/rules", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.RulePage.self, from: data)
  }
  public func createRule(headers: CreateRuleHeaders, body: DashboardAPI.RuleInput) async throws -> DashboardAPI.Rule {
    let queryValues: [String: String] = [:]
    var headersValues: [String: String] = [:]
    if let value = headers.`xCSRFToken` { headersValues["X-CSRF-Token"] = String(describing: value) }
    headersValues["Idempotency-Key"] = String(describing: headers.`idempotencyKey`)
    let request = DashboardHTTPRequest(method: "POST", path: "/api/v1/rules", query: queryValues, headers: headersValues, body: try JSONEncoder().encode(body))
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Rule.self, from: data)
  }
  public func updateRule(ruleId: String, headers: UpdateRuleHeaders, body: DashboardAPI.RuleInput) async throws -> DashboardAPI.Rule {
    let queryValues: [String: String] = [:]
    var headersValues: [String: String] = [:]
    if let value = headers.`xCSRFToken` { headersValues["X-CSRF-Token"] = String(describing: value) }
    headersValues["If-Match"] = String(describing: headers.`ifMatch`)
    let request = DashboardHTTPRequest(method: "PUT", path: "/api/v1/rules/\(segment(ruleId))", query: queryValues, headers: headersValues, body: try JSONEncoder().encode(body))
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.Rule.self, from: data)
  }
  public func targets(query: TargetsQuery = .init()) async throws -> DashboardAPI.TargetPage {
    var queryValues: [String: String] = [:]
    if let value = query.`scope` { queryValues["scope"] = String(describing: value) }
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/targets", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.TargetPage.self, from: data)
  }
  public func workloads(kind: String, query: WorkloadsQuery = .init()) async throws -> DashboardAPI.WorkloadPage {
    var queryValues: [String: String] = [:]
    if let value = query.`scope` { queryValues["scope"] = String(describing: value) }
    if let value = query.`cursor` { queryValues["cursor"] = String(describing: value) }
    if let value = query.`limit` { queryValues["limit"] = String(describing: value) }
    let headersValues: [String: String] = [:]
    let request = DashboardHTTPRequest(method: "GET", path: "/api/v1/workloads/\(segment(kind))", query: queryValues, headers: headersValues, body: nil)
    let data = try await transport.send(request)
    return try JSONDecoder().decode(DashboardAPI.WorkloadPage.self, from: data)
  }
}
